<?php /** @var M2S\ProductAttachment\Block\Adminhtml\Product\Edit\Tab\Attachment $block **/ ?>
<?php if ($items = $block->getItems()): ?>
    <table class="attachment-list">
        <thead>
        <tr>
            <td><?= __('ID'); ?></td>
            <td><?= __('Image'); ?></td>
            <td><?= __('File Name'); ?></td>
            <td><?= __('Created At'); ?></td>
            <td><?= __('Status'); ?></td>
        </tr>
        </thead>
        <?php foreach ($items as $item): ?>
            <?php $type = $block->getItemByType($item); ?>
            <?php $fileName = $item->getFileName(); ?>
            <?php $filePath = $item->getAttachmentPath(); ?>
        <tr>
        <td><?=  $item->getId(); ?></td>
        <td>
            <?php if ($type == 'application/pdf'):?>
                <a href="<?php echo $filePath; ?>"> <img target="_blank" src="<?php echo $this->getViewFileUrl('M2S_ProductAttachment::images/pdf.png'); ?>" alt="<?php echo $fileName ?>" /> </a>
            <?php else: ?>
                <img src=" <?php echo $filePath; ?>" alt="<?php echo $fileName ?>"/>
           <?php endif; ?>
        </td>
        <td><?=  $item->getFileName(); ?></td>
        <td><?=  $item->getCreatedAt(); ?></td>
        <td><?=  $item->getStatus(); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>

<?php endif; ?>
